# name: Caching Npm

# on: workflow_dispatch

# jobs:
#     demo:
#         runs-on: ubuntu-latest

#         steps:
#             - name: checkout the code
#               uses: actions/checkout@v7

#             - name: install Node.js
#               uses: actions/setup-node@v6
#               with:
#                 node-version: '20'
#             - name: Cache
#               id: Cache
#               uses: actions/cache@v6
#               with: 
#                 path: ~/.npm
#                 key: ${{runner.os}}-npm${{hashFiles('node_application')}}
#                 resore-path:
#                     ${{runner.os}}-npm
#             - name: Install Dependecies
#               run: npm install
#             - name: Application
#               run: npm install &


name: Caching Npm

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm install

      - name: Application
        run: npm start

