name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # this is machine once action done this will be deleted by default

    steps:
      - name: Checkout
        uses: actions/checkout@v5 # like argument

      - name: Install Node.js
        uses: actions/setup-node@v6 # like argument mandatory
        with:
          node-version: 22 # this version will be installed inside runner (ubuntu-latest)

      - name: Start application
        run: npm start &

      - name: Wait for the application to boot
        run: sleep 5

      - name: Check the health
        run: curl -I "http://localhost:3000" || exit 1
         
            



