name: Demo Composite Action

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run Demo Composite Action
        uses: ./.github/actions/demo  
        with:
          who-to-greet: "Virat Kohli"