name: data send 1 to many

on: workflow_dispatch

jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            job1_outputs: "${{steps.step2.outputs.msg}}" # step 2 generated data op we are storing in job1_outputs  
        steps:
         - name: set a variable
           id: step1
           run: echo "msg=its id defined " >> $GITHUB_OUTPUT

         - name: set a variables #this step data will store in job1_output
           id: step2
           run : echo "msg=This is job1 and step 2 output " >> $GITHUB_OUTPUT

         - name: get the op from step
           id: step3
           run: echo "output from the variable ${{steps.step1.outputs.msg}}" 
   
    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name : This is data from job1 to job2
              run: echo "${{needs.job1.outputs.job1_outputs}}"
    job3:
      runs-on: ubuntu-latest
      steps:
        - name: this is job 3
          run: echo "job three 3"
