name: Sequensial job

on: [push]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: First
              run: exit 1
    job2:
        needs: job1 #job 1 must complete
        if: ${{always()}} #condition always() if job1 run or fail job2 will execute
        runs-on: ubuntu-latest
        steps:
            - name: Third Job
              run: echo "Third job"
    job3:
        needs: job2 #job 1 must 
        runs-on: ubuntu-latest
        steps:
            - name: third
              run: echo this is third
