name: Matrix

on: 
    workflow_dispatch:

jobs:
    job:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
              version: [18,20] #Two jobs run 2 versions 
              os: [ubuntu,windows] #each os runs 2 jobs U2 W2
        steps:
            - name: install node
              uses: actions/setup-node@v6
              with :
                node-version: ${{matrix.version}}


